# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SaveMoney',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.CharField(max_length=200)),
                ('money', models.IntegerField(default=0)),
                ('dateTime', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
